#spring.datasource.url=jdbc:h2:mem:testdb
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social-media-database
    username: social-media-user
    password: dummypassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    user:
      name: username
      password: password